apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-servers
spec:
  selector:
    matchLabels:
      app: web-servers
  replicas: 1
  template:
    metadata:
      labels:
        app: web-servers
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 80
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
