apiVersion: v1
kind: Service
metadata:
  name: web-servers
  labels:
    app: web-servers
spec:
  ports:
  - name: apache
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-servers
  type: LoadBalancer
